/*
 *Allows users to enter in sales reporting info from the GUI and passes the 
 * information to a file and saves all entered info.
 * There are three frames. The first one collects the reps info. 
 * Frame two "Sales Info Frame" collects info on the sale.
 * Frame "Display Text" shows the user what was enterd from frame 1 & 2.
 */
package it252;

/**
 * @author Angelo Barcelo
 * angelobarcelo@hotmail.com
 */
public class DisplayText extends javax.swing.JFrame
{

String repId; 
String repFirstName;
String repLastName;
String SupplyTab;
Double supplieSales; 
Double bookSales; 
Double paperSales; 
String salesDist; 
String contactMeth;
    /**
     * Creates new form DisplayText
     */

    //Passes variables from 2nd frame into this frame 
    public DisplayText(String repId, String repFirstName, String repLastName, Double supplieSales,  Double bookSales, 
                Double paperSales,  String salesDist,  String contactMeth)
    {
        this.repId= repId;
        this.repFirstName = repFirstName;
        this.repLastName = repLastName;
        this.SupplyTab = SupplyTab;
        this.supplieSales = supplieSales; 
        this.bookSales = bookSales; 
        this.paperSales = paperSales; 
        this.salesDist = salesDist;
        this.contactMeth = contactMeth;
        
        initComponents();
        
        //Sets the text area to variables entered in frame 1 & 2
        Display.setText(repId+" "+ repFirstName+ " "+ repLastName+" SUPPLIES "+supplieSales +
                " BOOKS " + bookSales + " PAPER " + paperSales + " " + salesDist +
                " " + contactMeth);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Display = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Display.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                DisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DisplayActionPerformed
    {//GEN-HEADEREND:event_DisplayActionPerformed

    }//GEN-LAST:event_DisplayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(DisplayText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(DisplayText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(DisplayText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(DisplayText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
   
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Display;
    // End of variables declaration//GEN-END:variables
}
