/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it252;
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import java.io.BufferedReader;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.io.FileReader;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.JTableHeader;
/**
 *
 * @author Truth
 */
public class RepFrame extends javax.swing.JFrame
{

    /**
     * Creates new form NewJFrame
     */
    String repId;
    public RepFrame()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        EnterButton = new javax.swing.JButton();
        QuitButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        RepId = new javax.swing.JTextField();
        RepLastName = new javax.swing.JTextField();
        RepFirstName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Representatives's Info");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        EnterButton.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        EnterButton.setText("Enter");
        EnterButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EnterButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EnterButtonActionPerformed(evt);
            }
        });

        QuitButton.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        QuitButton.setText("Quit");
        QuitButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        QuitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                QuitButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Please enter your rep info");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it252/Welcome.PNG"))); // NOI18N
        jLabel3.setText("jLabel3");

        RepId.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        RepId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RepId.setText("Sales Representative's ID");
        RepId.setToolTipText("Enter the sales representative ID here");
        RepId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RepId.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                RepIdFocusLost(evt);
            }
        });
        RepId.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                RepIdMouseClicked(evt);
            }
        });
        RepId.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RepIdActionPerformed(evt);
            }
        });
        RepId.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                RepIdPropertyChange(evt);
            }
        });

        RepLastName.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        RepLastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RepLastName.setText("Sales Reps Last Name");
        RepLastName.setToolTipText("Enter the sales representatives last name here");
        RepLastName.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RepLastNameActionPerformed(evt);
            }
        });

        RepFirstName.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        RepFirstName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RepFirstName.setText("Sales Reps First Name");
        RepFirstName.setToolTipText("Enter the sales representatives first name here");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RepId, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RepFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RepLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RepId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(RepFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(RepLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(EnterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(QuitButton)
                .addGap(118, 118, 118))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuitButton)
                    .addComponent(EnterButton))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_QuitButtonActionPerformed
    {//GEN-HEADEREND:event_QuitButtonActionPerformed
        System.exit(1);
    }//GEN-LAST:event_QuitButtonActionPerformed
 
    private void RepIdActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RepIdActionPerformed
    {//GEN-HEADEREND:event_RepIdActionPerformed
     
        repId= RepId.getText();       // TODO add your handling code here:
    }//GEN-LAST:event_RepIdActionPerformed
 
    String getRepId()
    {
        return repId;
    }
    private void RepLastNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RepLastNameActionPerformed
    {//GEN-HEADEREND:event_RepLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RepLastNameActionPerformed

    private void EnterButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EnterButtonActionPerformed
    {//GEN-HEADEREND:event_EnterButtonActionPerformed
        setVisible(false);
        salesInfoFrame hello2 = new salesInfoFrame();
        hello2.setVisible(true);
    }//GEN-LAST:event_EnterButtonActionPerformed

    private void RepIdMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RepIdMouseClicked
    {//GEN-HEADEREND:event_RepIdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RepIdMouseClicked

    private void RepIdPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_RepIdPropertyChange
    {//GEN-HEADEREND:event_RepIdPropertyChange
        repId = (String)RepId.getText();// TODO add your handling code here:
    }//GEN-LAST:event_RepIdPropertyChange

    private void RepIdFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_RepIdFocusLost
    {//GEN-HEADEREND:event_RepIdFocusLost
        repId = RepId.getText();
        System.out.println("Lost Focuse");// TODO add your handling code here:
    }//GEN-LAST:event_RepIdFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RepFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RepFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RepFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RepFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new RepFrame().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnterButton;
    private javax.swing.JButton QuitButton;
    private javax.swing.JTextField RepFirstName;
    private javax.swing.JTextField RepId;
    private javax.swing.JTextField RepLastName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
