/*
 *This program is a total sales record keeper. It takes the entered info and 
 *writes a file with the entered info. It has two main frames: frame 1 "RepInfo"
 *is all the reps info. Frame 2 "SalesInfo" is all the sales totals info. The 3rd 
 *frame "DisplayText" is ment only to display information to the user...Might 
 *delete it later. 
 *
 *If you see "Added for Ui experiance ++" == Means this feature or code was only 
 *added to make the user experiance better. It is not part or functionality of 
 *the program or requirments unless other wise stated.
 */
package it252;

import javax.swing.JOptionPane;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author Angelo Barcelo
 * angelobarcelo@hotmail.com
 */
public class SalesInfo extends javax.swing.JFrame
{

String repId;
String repFirstName;
String repLastName;
Double supplieSales;
Double bookSales;
Double paperSales;
Double totalSales;
String salesDist;
String contactMeth;
    /**
     * Creates new form SalesInfo
     */
    public SalesInfo(String contactMeth,String repFirstName,String repId,String repLastName,String salesDist)
    {
        this.repId = repId;
        this.repFirstName = repFirstName;
        this.repLastName = repLastName;
        this.salesDist = salesDist;
        this.contactMeth = contactMeth;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        suppliesTab = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        book_text = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        supplies_Text = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        paper_Text = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        displayButton = new javax.swing.JButton();
        QuitButton = new javax.swing.JButton();
        EnterButton = new javax.swing.JButton();
        EvaluateButton = new javax.swing.JButton();
        changeRepInfoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales Information");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(50, 50));

        suppliesTab.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N

        book_text.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        book_text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        book_text.setText("Book total sales");
        book_text.setToolTipText("Enter book total sales here. No $, just numbers please");
        book_text.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                book_textFocusGained(evt);
            }
        });
        book_text.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                book_textActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(book_text, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(book_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        suppliesTab.addTab("Books", jPanel2);

        supplies_Text.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        supplies_Text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        supplies_Text.setText("Supplies total sales");
        supplies_Text.setToolTipText("Enter the supplies total sales here. NO $, just numbers please");
        supplies_Text.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                supplies_TextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(supplies_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(supplies_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        suppliesTab.addTab("Office Supplies", jPanel1);

        paper_Text.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        paper_Text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paper_Text.setText("Paper total sales");
        paper_Text.setToolTipText("Enter the paper total sales here. NO $, just numbers please");
        paper_Text.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                paper_TextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paper_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(paper_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        suppliesTab.addTab("Paper", jPanel3);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it252/Info.PNG"))); // NOI18N

        displayButton.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        displayButton.setText("Display");
        displayButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                displayButtonActionPerformed(evt);
            }
        });

        QuitButton.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        QuitButton.setText("Quit");
        QuitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                QuitButtonActionPerformed(evt);
            }
        });

        EnterButton.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        EnterButton.setText("Enter");
        EnterButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EnterButtonActionPerformed(evt);
            }
        });

        EvaluateButton.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        EvaluateButton.setText("Evaluate");
        EvaluateButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EvaluateButtonActionPerformed(evt);
            }
        });

        changeRepInfoButton.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        changeRepInfoButton.setText("Change Rep Info");
        changeRepInfoButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                changeRepInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(suppliesTab, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EnterButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changeRepInfoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EvaluateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuitButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(suppliesTab, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnterButton)
                    .addComponent(changeRepInfoButton)
                    .addComponent(displayButton)
                    .addComponent(EvaluateButton)
                    .addComponent(QuitButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_displayButtonActionPerformed
    {//GEN-HEADEREND:event_displayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayButtonActionPerformed

    private void QuitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_QuitButtonActionPerformed
    {//GEN-HEADEREND:event_QuitButtonActionPerformed
        //Exits the system when quit button entered
        System.exit(1);
    }//GEN-LAST:event_QuitButtonActionPerformed

    private void EnterButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EnterButtonActionPerformed
    {//GEN-HEADEREND:event_EnterButtonActionPerformed
        //Gets the text from book sales text area and converts to double
        bookSales = Double.parseDouble(book_text.getText());
        
        //Gets the text from supplies sales text area and converts to double
        supplieSales = Double.parseDouble(supplies_Text.getText());
        
        //Gets the text from paper sales text area and converts to double
        paperSales = Double.parseDouble(paper_Text.getText());
        
        book_text.setText("book total sales");
        supplies_Text.setText("Supplies total sales");
        paper_Text.setText("Paper total sales");
        
        //Creates formated string to send to file
        String textFile = repId + " " +repFirstName + " " + repLastName + 
                " SUPPLIES " + supplieSales + " BOOKS " +bookSales + " PAPER " +
                paperSales + " " + salesDist + " " +contactMeth;
         
        try
        {
            //Creats the file in the users "main" path. Only works for windows users
            File file = new File(System.getProperty("user.home")+"\\SalesRep.txt");
            
            FileWriter writter = new FileWriter(file,true);
            
            BufferedWriter buffWrite = new BufferedWriter(writter);
            
            PrintWriter pWriter = new PrintWriter(buffWrite);
             
            pWriter.println(textFile);
            
            buffWrite.close();
            
            //Added for Ui experiance ++ lets the use know save is done & no errors
            JOptionPane.showMessageDialog(null, "All done! Your file has been "
                    + "saved to " + System.getProperty
                    ("user.home")+"\\salesrep.txt");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
           
        //Calls the 3rd frame and passes variables from frame 1&2
        //DisplayText text = new DisplayText(repId, repFirstName, repLastName, supplieSales,  bookSales, 
        //        paperSales,  salesDist,  contactMeth);

        //Makes 3rd frame visibal
        //text.setVisible(true);
    }//GEN-LAST:event_EnterButtonActionPerformed

    private void changeRepInfoButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_changeRepInfoButtonActionPerformed
    {//GEN-HEADEREND:event_changeRepInfoButtonActionPerformed
        //Calls the first frame
        RepInfo repFrame = new RepInfo();
        
        //Makes frame 2 disapear
        setVisible(false);
        
        //Makes frame 1 visable
        repFrame.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_changeRepInfoButtonActionPerformed

    private void book_textActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_book_textActionPerformed
    {//GEN-HEADEREND:event_book_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_textActionPerformed

    private void supplies_TextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_supplies_TextActionPerformed
    {//GEN-HEADEREND:event_supplies_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplies_TextActionPerformed

    private void paper_TextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_paper_TextActionPerformed
    {//GEN-HEADEREND:event_paper_TextActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_paper_TextActionPerformed

    private void book_textFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_book_textFocusGained
    {//GEN-HEADEREND:event_book_textFocusGained
        //Added for Ui experiance ++ when user clicks in text area it clear all text
        book_text.setText(null);// TODO add your handling code here:
    }//GEN-LAST:event_book_textFocusGained

    private void EvaluateButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EvaluateButtonActionPerformed
    {//GEN-HEADEREND:event_EvaluateButtonActionPerformed
        ArrayList<String> salesInfo = new ArrayList<>();
        try 
        {
            Scanner scan = new Scanner(new File(System.getProperty("user.home")+"\\SalesRep.txt")); 
            while (scan.hasNext())
            {
                repId = scan.next();
                repFirstName = scan.next();
                repLastName = scan.next();
                String suppliesLabel = scan.next();
                supplieSales = scan.nextDouble();
                String bookLabel = scan.next();
                bookSales = scan.nextDouble();
                String paperLabel = scan.next();
                paperSales = scan.nextDouble();
                salesDist = scan.next();
                contactMeth = scan.next();
                totalSales = supplieSales+bookSales+paperSales;
            
                if (totalSales>=8000)
                {
                    try
                    {
                        String textFile2 = repId + " " +repFirstName + " " + repLastName + " "+
                        suppliesLabel + " " + supplieSales + " " + bookLabel + " "+ bookSales + " " +paperLabel + " " +
                        paperSales + " " + salesDist + " " +contactMeth;
                        //Creats the file in the users "main" path. Only works for windows users
                        File file2 = new File(System.getProperty("user.home")+"\\Stars.txt");
            
                        FileWriter writter = new FileWriter(file2,true);
            
                        BufferedWriter buffWrite = new BufferedWriter(writter);
            
                        PrintWriter pWriter = new PrintWriter(buffWrite);
             
                        pWriter.println(textFile2);
            
                        buffWrite.close();
            
                        //Added for Ui experiance ++ lets the use know save is done & no errors
                        JOptionPane.showMessageDialog(null, "Found a new star and add them to the file @: " + System.getProperty
                        ("user.home")+"\\stars.txt");
                    }
                    catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(this, e);
                    }
                };
            }
        }
        catch(Exception e)
        {
        }
    }//GEN-LAST:event_EvaluateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(SalesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(SalesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(SalesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(SalesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnterButton;
    private javax.swing.JButton EvaluateButton;
    private javax.swing.JButton QuitButton;
    private javax.swing.JTextField book_text;
    private javax.swing.JButton changeRepInfoButton;
    private javax.swing.JButton displayButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField paper_Text;
    private javax.swing.JTabbedPane suppliesTab;
    private javax.swing.JTextField supplies_Text;
    // End of variables declaration//GEN-END:variables
}
