/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it252;

/**
 *
 * @author Truth
 */
public class salesInfoFrame extends javax.swing.JFrame
{
String SalesDist;
String test;
String full;
    /**
     * Creates new form salesInfoFrame
     */
    public salesInfoFrame()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        EnterButton = new javax.swing.JButton();
        SuppliesTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        TotalSales = new javax.swing.JTextField();
        SalesDistrict = new javax.swing.JComboBox();
        contactMethod = new javax.swing.JComboBox();
        EvaluateButton = new javax.swing.JButton();
        displayButton = new javax.swing.JButton();
        QuitButton = new javax.swing.JButton();
        TitleText = new javax.swing.JLabel();
        Image2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales Information");

        EnterButton.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        EnterButton.setText("Enter");
        EnterButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EnterButtonActionPerformed(evt);
            }
        });

        SuppliesTab.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        SuppliesTab.addTab("Office Supplies", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        SuppliesTab.addTab("Books", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        SuppliesTab.addTab("Paper", jPanel3);

        TotalSales.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        TotalSales.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TotalSales.setText("Total Sales for the Year");
        TotalSales.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TotalSalesActionPerformed(evt);
            }
        });

        SalesDistrict.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        SalesDistrict.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sales district:", "North", "South", "East", "West" }));
        SalesDistrict.setToolTipText("Please enter was district the sale is for.");
        SalesDistrict.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                SalesDistrictFocusLost(evt);
            }
        });
        SalesDistrict.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SalesDistrictActionPerformed(evt);
            }
        });
        SalesDistrict.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                SalesDistrictPropertyChange(evt);
            }
        });

        contactMethod.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        contactMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Preferred  contact method:", "Phone", "E-mail", "Visit" }));

        EvaluateButton.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        EvaluateButton.setText("Evaluate");

        displayButton.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        displayButton.setText("Display");
        displayButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                displayButtonActionPerformed(evt);
            }
        });

        QuitButton.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        QuitButton.setText("Quit");
        QuitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                QuitButtonActionPerformed(evt);
            }
        });

        TitleText.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        TitleText.setText("Select the information for the sales being entered");

        Image2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it252/Info.PNG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Image2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EnterButton)
                        .addGap(55, 55, 55)
                        .addComponent(displayButton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SuppliesTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EvaluateButton)
                                .addGap(52, 52, 52)
                                .addComponent(QuitButton)))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TotalSales)
                            .addComponent(contactMethod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SalesDistrict, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TitleText)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleText)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SuppliesTab, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TotalSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SalesDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(contactMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Image2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnterButton)
                    .addComponent(displayButton)
                    .addComponent(EvaluateButton)
                    .addComponent(QuitButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_displayButtonActionPerformed
    {//GEN-HEADEREND:event_displayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayButtonActionPerformed

    private void EnterButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EnterButtonActionPerformed
    {//GEN-HEADEREND:event_EnterButtonActionPerformed
       String TS = TotalSales.getSelectedText();
       String SD = String.valueOf(SalesDistrict.getSelectedItem());
       String ST = String.valueOf(SuppliesTab.getSelectedComponent());
       
       full = ("TS "+ "SD "+ "ST");
       DisplayText text = new DisplayText();
       
       SalesDistrict.getSelectedItem(); // TODO add your handling code here:
       text.setVisible(true);
    }//GEN-LAST:event_EnterButtonActionPerformed
    public String getText()
    {
    return full; 
    }
    
    public String getComboBox()
    { 
        return SalesDist;
    }
    private void QuitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_QuitButtonActionPerformed
    {//GEN-HEADEREND:event_QuitButtonActionPerformed
        System.exit(1);
    }//GEN-LAST:event_QuitButtonActionPerformed

    private void TotalSalesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TotalSalesActionPerformed
    {//GEN-HEADEREND:event_TotalSalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalSalesActionPerformed

    private void SalesDistrictActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SalesDistrictActionPerformed
    {//GEN-HEADEREND:event_SalesDistrictActionPerformed
        SalesDistrict.getSelectedItem();
        SalesDist = (String)SalesDistrict.getSelectedItem();// TODO add your handling code here:
           SalesDistrict.addActionListener(SalesDistrict);
    }//GEN-LAST:event_SalesDistrictActionPerformed

    private void SalesDistrictFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_SalesDistrictFocusLost
    {//GEN-HEADEREND:event_SalesDistrictFocusLost
        
        SalesDist = (String)SalesDistrict.getName();// TODO add your handling code here:
           SalesDistrict.addActionListener(SalesDistrict);// TODO add your handling code here:
   
    }//GEN-LAST:event_SalesDistrictFocusLost

    private void SalesDistrictPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_SalesDistrictPropertyChange
    {//GEN-HEADEREND:event_SalesDistrictPropertyChange
         test = SalesDistrict.getName(); // TODO add your handling code here:
    }//GEN-LAST:event_SalesDistrictPropertyChange
    public String getTest()
    {
        return test;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(salesInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(salesInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(salesInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(salesInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new salesInfoFrame().setVisible(true);
                
            }
        });
    }
    public String combo()
            {
            return SalesDist=(String)SalesDistrict.getSelectedItem();
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnterButton;
    private javax.swing.JButton EvaluateButton;
    private javax.swing.JLabel Image2;
    private javax.swing.JButton QuitButton;
    private javax.swing.JComboBox SalesDistrict;
    private javax.swing.JTabbedPane SuppliesTab;
    private javax.swing.JLabel TitleText;
    private javax.swing.JTextField TotalSales;
    private javax.swing.JComboBox contactMethod;
    private javax.swing.JButton displayButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
